### ISSUE TITLE
do not tag with 'biography' if the draft is already tagged

### ISSUE THREAD

**Issue by Svetlana-T** [WPAFC/afch-rewrite#101]
Some people mark drafts with wikiproject tags prior to the time of their approval, then when approving the draft the script adds 'biography' mark if the reviewer ticks a box; this is good but the script currently does not notice the presence of the existing mark and as a result it becomes added twice. This should be resolved by checking for the presense of existing wikiproject tags at the talk page of the article before adding new ones.

**Comment by SvetlanaTkachenko** [comment]
Is there any progress on this, please., @enterprisey

**Comment by SvetlanaTkachenko** [comment]
@enterprisey : Please address this.

**Comment by Svetlana-T** [comment]
Thanks Enterprisey! Happy NeYear. 

Is it already deployed?

**Comment by enterprisey** [comment]
Yup.
