### ISSUE TITLE
Can't handle slashes in article titles

### ISSUE THREAD

**Issue by enterprisey** [WPAFC/afch-rewrite#110]
See https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:WikiProject_Articles_for_creation&oldid=prev&diff=896575638. We should probably provide adequate warning, and at least try to handle this sensibly.

**Comment by NovemLinguae** [comment]
This was recently mentioned again at [[WT:AFCR]]. https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:WikiProject_Articles_for_creation&diff=1031209195&oldid=1031109312&diffmode=source
