### ISSUE TITLE
Remove {{draft}}/{{draft article}} templates on accept

### ISSUE THREAD

**Issue by enterprisey** [WPAFC/afch-rewrite#124]
> Remove {{draft}}/{{draft article}} templates upon acceptance similar to removing the {{AFC submission}} template.

From [2pou, 21:03, 15 December 2020 (UTC)](https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation/2020_5#2_AFC_script_feature_suggestions) ([permalink](https://en.wikipedia.org/w/index.php?diff=994462554))

**Comment by enterprisey** [comment]
Instructions: Add code to `AFCH.Text.prototype.cleanUp` to remove the {{draft}} and {{draft article}} templates. Use the "i" (ignore case) flag in the regular expression, because template names are case-insensitive (except for the first character).

**Comment by satcasm** [comment]
Hi, I would like to work on this issue. Can you tell me how to get started?

**Comment by enterprisey** [comment]
@satcasm Sure, and thank you for offering to help! Some drafts use the [{{Draft article}}](https://en.wikipedia.org/wiki/Template:Draft_article) template to show a banner. Articles shouldn't include it. The function `AFCH.Text.prototype.cleanUp`, defined in [src/modules/submissions.js](https://github.com/WPAFC/afch-rewrite/blob/master/src/modules/submissions.js), is responsible for cleaning up things that shouldn't be included in articles. The solution is to add some code to the `if ( isAccept )` statement that removes any usage of {{Draft article}}; this should probably be done via regex, just like the rest of the code there.

Now, there are two things to consider:

1. {{Draft article}} has three alternative names, but only one is used: {{Draft}}. So your code should assume the "` article`" part is optional, and be case-insensitive.
2. The template has a parameter, `text`, that seems to take arbitrary text. That text could contain templates, which could mess up. I would therefore recommend not deleting instances of {{Draft}} or {{Draft article}} that match `\s*\|\s*text\s*=`.

For development, I would recommend making a draft that uses both, and some parameters, at https://test.wikipedia.org (your Wikipedia account should work there too), and then running your modified version of the script on it. (At #137 I'm trying to make this easier.)

Please feel free to let me know if you run into any issues here or in [our Zulip channel](https://wikimedia.zulipchat.com/#narrow/stream/273783-enwiki-afch). Thanks again!

**Comment by satcasm** [comment]
Thanks @enterprisey , I would start right away.

**Comment by enterprisey** [comment]
if you write AFCH.consts.mockItUp = true in your browser console or add it to src/afch.js and then try accepting https://test.wikipedia.org/wiki/Draft:Testing_AFCH (in its current version, revid 466015, there are lots of instances of {{draft article}} and {{draft}}), you'll see that one of the JSON objects printed to the console has the new text of the article, and that in that text none of the templates under "these should all be removed" were touched - the goal is to make sure all of them are gone, and that none of the templates under "none of these should be removed" were removed

**Comment by Adityachaturvedi2906** [comment]
Hi, I would like to work on this issue, can you please guide me further?

**Comment by enterprisey** [comment]
(note for posterity that Adityachaturvedi2906 (most recent commenter) has already claimed #105 )

**Comment by enterprisey** [comment]
Fixed!
