### ISSUE TITLE
Handle {{Draft categories}}

### ISSUE THREAD

**Issue by enterprisey** [WPAFC/afch-rewrite#125]
> Remove {{Draft categories}} templates along with the colons in categories using the WP:COLON trick. Sometimes drafts will use that template instead of the colon trick.

See also https://en.wikipedia.org/w/index.php?diff=994460689, in which the use of {{Draft categories}} is *not* handled.

From [2pou, 21:03, 15 December 2020 (UTC)](https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation/2020_5#2_AFC_script_feature_suggestions) ([permalink](https://en.wikipedia.org/w/index.php?diff=994462554))

**Comment by satcasm** [comment]
I would like to work on it. Can you brief me about it?
Much appreciated.

**Comment by enterprisey** [comment]
@satcasm Not too complicated - {{Draft categories|*whatever*}} should be replaced with just *whatever* when cleaning an accepted submission (in cleanUp with isAccept set to true). I think we might also do some other formatting of categories (removing extra newlines, maybe?) so it would be nice to ensure that happens to those categories that were inside {{Draft categories}}. Also, categories should be at the bottom, per [MOS:ORDER](https://en.wikipedia.org/wiki/MOS:ORDER). (I don't know if we already enforce that for regular categories, but if we do, we should also enforce it for these. If we don't, feel free to also implement that - putting all categories at the bottom.)

**Comment by enterprisey** [comment]
Fixed.
