### ISSUE TITLE
Should not duplicate existing wikiproject tags on talk page

### ISSUE THREAD

**Issue by siddharthvp** [WPAFC/afch-rewrite#148]
See [this edit](https://en.wikipedia.org/w/index.php?title=Talk:Yazmin_Aziz_(musician)&type=revision&diff=985561188&oldid=985561170&diffmode=source), in which the Biography project tag that already existed on the talk page was duplicated.

Suggested fix: parse the talk page for existing wikiproject tags[1], show them using the jquery.chosen select menu allowing the reviewer to remove existing ones, add new ones, etc. 

This task is also a blocker for the deployment of AFC-submit-wizard discussed [here](https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation/2020_4#Overhauling_draft_submission_process_using_javascript).

----

[1] some code for this exists here: [function extractWikiProjectTagsFromText](https://en.wikipedia.org/wiki/User:SD0001/AFC-submit-wizard.js#L-377), which doesn't work 100% of the time but good enough I think.

**Comment by primefac** [comment]
Wasn't this already fixed?

**Comment by siddharthvp** [comment]
Let me see. Last I checked may have been in October ...

**Comment by siddharthvp** [comment]
https://github.com/WPAFC/afch-rewrite/commit/4ad387d9e7173137e8db6b3bbbec9df631069198 suggests yes, thanks @enterprisey!
