### ISSUE TITLE
properly define "type" so that FFU and AFC/R can be loaded

### ISSUE THREAD

**Issue by Technical-13** [WPAFC/afch-rewrite#15]
If this script is going live in a couple days, it should have FFU and AFC/R functionality.  I figured out what I was missing and AFC/R in the beta version of the script was working (I just wasn't seeing the review button because it was hidden in a dropdown from another script I use that collapses all of the portletlinks in that section).  I've requested the beta AFC/R pushed live (to fix the immediate issue) and there is unanimous support at the moment for moving RW to live.

**Comment by enterprisey** [comment]
As of the current day, FFU and AFC/R have their own scripts.
