### ISSUE TITLE
Edit summary contains the text "undefined"

### ISSUE THREAD

**Issue by NovemLinguae** [WPAFC/afch-rewrite#150]
Edit summary contains the text "undefined". Happening in all my submissions today. Problem with the version variable? Problem with its scope?

Example edit summaries:
    - "Submitting (AFCH undefined)"
    - "Rejecting submission: e - Topic is contrary to the purpose of Wikipedia (AFCH undefined)"

Diffs:
- https://en.wikipedia.org/w/index.php?title=Draft:Testing&diff=prev&oldid=1009813077
- https://en.wikipedia.org/w/index.php?title=Draft:Testing&diff=prev&oldid=1009813124
- https://en.wikipedia.org/w/index.php?title=User_talk:MarinerJim&diff=prev&oldid=1009840695
- https://en.wikipedia.org/w/index.php?title=Draft:Jack_Spring_(film_director)&diff=prev&oldid=1009840698
- https://en.wikipedia.org/w/index.php?title=Draft:Call_of_War_(Mobile/_PC_strategy_game)&diff=prev&oldid=1009828122
- https://en.wikipedia.org/w/index.php?title=User_talk:VtechPrototypeCollector&diff=prev&oldid=1009828121
- etc.

**Comment by enterprisey** [comment]
fixed 89edacb18511
