### ISSUE TITLE
summaryAd (edit summary 'tag') contains 'undefined' rather than version

### ISSUE THREAD

**Issue by rwjuk** [WPAFC/afch-rewrite#151]
Example edit: https://en.wikipedia.org/w/index.php?title=Draft:FoxyMoron&diff=prev&oldid=1009804371

It seems [this line](https://github.com/WPAFC/afch-rewrite/blob/3c7b378ba53c86fea47d4e9f0b7711f5db00304e/src/modules/core.js#L79) is to blame here. I imagine (for reasons I've not yet determined) `AFCH.consts.version` is undefined at this point, hence `summaryAd` doesn't get composed properly.

**Comment by rwjuk** [comment]
Dupe of #150. Oops. Might be worth keeping this for where the problem seems to be.

**Comment by enterprisey** [comment]
fixed 89edacb18511
