### ISSUE TITLE
Informing non-autoconfirmed users they can create articles directly in mainspace

### ISSUE THREAD

**Issue by Pahunkat** [WPAFC/afch-rewrite#152]
Example: Accepting [https://en.wikipedia.org/wiki/Joll](url), a DAB created by a non-autoconfirmed user, leads to https://en.wikipedia.org/w/index.php?title=User_talk:Lijomlle&oldid=1009887462 being generated on the user's talk page which states that they can directly create articles in mainspace.

This has been replicated by another reviewer accepting https://en.wikipedia.org/wiki/Jolls

Issue 150/151 was also replicated during the course of both reviews.

**Comment by enterprisey** [comment]
Although it looks like a bug, apparently the template uses CSS, so it'll show correctly for non-autoconfirmed users: https://en.wikipedia.org/wiki/Template:AfC_talk#Note
