### ISSUE TITLE
Rename "Decline submission" button to "Reject submission" when "Reject" radio button selected

### ISSUE THREAD

**Issue by enterprisey** [WPAFC/afch-rewrite#156]

**Comment by vartikaSaxena** [comment]
Hey, @enterprisey I want to work on this issue, could you please guide me about it...

**Comment by enterprisey** [comment]
@vartikaSaxena hi! thank you for your interest. unfortunately issue #145 is currently being worked on by someone, and this issue would be fixed as a result of that work. I should have closed this issue at that point but forgot to; apologies. Please pick another issue, or ping me in a new topic in [our Zulip channel](https://wikimedia.zulipchat.com/#narrow/stream/273783-enwiki-afch) so we can talk about an appropriate issue to work on.

**Comment by vartikaSaxena** [comment]
Aright. No problem

I would surely find some other issue to work on.
Since I am a beginner at this, it would be great if you could assign me
some beginner issues.
