### ISSUE TITLE
User preference /or/ better debugging tools?

### ISSUE THREAD

**Issue by Technical-13** [WPAFC/afch-rewrite#16]
Add a dropdown that will allow the script to load the various versions of the script as a dropdown to make version switching easier for debugging purposes.  Will add details and try to put together a pull request in a couple weeks.

**Comment by enterprisey** [comment]
Script switching can be handled by other tooling. I don't think this is an especially common use-case. WONTFIX; patch welcome, of course, but again I really don't see anyone using this besides developers, who could just roll their own stuff.

Also, these days there's just one version of the script; back then we had develop, beta, and the current release, and indeed the ability to switch between the two to investigate regressions would've been very convenient.
