### ISSUE TITLE
Display submission date and age on submitted drafts

### ISSUE THREAD

**Issue by NovemLinguae** [WPAFC/afch-rewrite#161]
Under "There are 5,533 pending submissions waiting for review", consider adding a line that says "This draft was submitted on April 5, 2021, and has been awaiting review for 47 days."

This is good info for a reviewer to have when visiting the draft for the first time, if they are coming from a list of drafts that is not in chronological order.

![image](https://user-images.githubusercontent.com/79697282/116398760-00ebda80-a7dd-11eb-8cf4-0604b9374b9c.png)

**Comment by primefac** [comment]
This is a template-side issue, not an AFCH issue. Should be placed at Template_talk:AfC_submission.

**Comment by NovemLinguae** [comment]
Ah true. I'll close this one. My apologies.
