### ISSUE TITLE
When accepting, remove {{Promising draft}} tag

### ISSUE THREAD

**Issue by NovemLinguae** [WPAFC/afch-rewrite#167]
Suggested by robertsky at [[WT:AFCR]]

https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:WikiProject_Articles_for_creation&diff=1032731561&oldid=1032728655

**Comment by abarsha** [comment]
Can i be assigned for this issue? i would love to work

**Comment by enterprisey** [comment]
@Yash-g17 does this one look interesting, or do you want to work on 106 with abarsha (who wants to work with the API)?

**Comment by abarsha** [comment]
@enterprisey  i want to work with API

**Comment by Yash-g17** [comment]
@enterprisey , Collaborating with abarsha seems good

**Comment by paul-111** [comment]
@Yash-g17  hey any further update?
