### ISSUE TITLE
WikiProject Women missing

### ISSUE THREAD

**Issue by NovemLinguae** [WPAFC/afch-rewrite#169]
When accepting a draft, there's a combo box with a list of WikiProjects. WikiProject Women is missing from it. There may be other WikiProjects missing too, but I think this one is worth a ticket, since half of all biographies probably need this tag.

**Comment by siddharthvp** [comment]
As of now, wikiprojects list is read off https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Articles_for_creation/WikiProject_templates.json that can be edited on-wiki. The list does include WikiProject Women.
