### ISSUE TITLE
"Cleaning up submission" edits should be minor edits

### ISSUE THREAD

**Issue by GeoffreyTrang** [WPAFC/afch-rewrite#178]
When one clicks on the "Clean submission" link, the draft will be cleaned up with an edit summary that says "Cleaning up submission (AFCH 0.9.1)". Such edits should be marked as minor edits by the script, but they currently are not minor edits.

**Comment by siddharthvp** [comment]
Done in #184. (@zanhecht you can mention "Closes #178" or "Fixes #178" in the commit message or PR to automatically trigger closure of the issue when the patch is merged).
