### ISSUE TITLE
Watch user talk page temporarily

### ISSUE THREAD

**Issue by Vukkyy** [WPAFC/afch-rewrite#179]
It would be nice to have a setting for changing how long you want to watch pages for using Watchlist Expiry - I kind of doubt you want to watch the same draft for 6 months.

**Comment by primefac** [comment]
I don't know why the script would be in charge of this, given how many other tools (including inbuilt ones) exist to set expiration times for the watchlist. And if you think about it, drafts get G13'd after six months, so having any sort of default at that time frame makes sense (though _does_ the script set watchlist times, or is that a personal-preferences type thing?).

**Comment by Vukkyy** [comment]
It appears as if I may have slightly forgotten how the script and API works when submitting this (oops) - it adds the user's talk page to the watchlist permanently when leaving a notice, not the draft, unless the draft is in root userspace (see #76).

Although... I'd imagine you probably don't expect a user to suddenly type a reply on their talk page 3 months later out of nowhere :p

If this were to be implemented, I think a separate request would have to be made to the [Watch API](https://www.mediawiki.org/wiki/API:Watch) to set expiration times, as the edit page API doesn't appear to support them.
