### ISSUE TITLE
Allow adding/editing shortdesc while accepting

### ISSUE THREAD

**Issue by siddharthvp** [WPAFC/afch-rewrite#190]
At the moment the acceptance form does ask for "Description of the subject" for bios, but the value entered seems to just go into the void. I'm assuming this is a remnant from when persondata used to be supported?

In any case, short description support would be good to have. From what I've seen, most folks tend to add appropriate shortdescs while submitting, but [sometimes not](https://en.wikipedia.org/w/index.php?title=Draft:Fireart_Studio&diff=1054313149&oldid=1054312400&diffmode=source). If it's shown while accepting, the reviewer could change it to something suitable.

**Comment by primefac** [comment]
There's been a push to update the "accept" values the reviewer needs to input, but I never thought to just change that description to a straight-up {{short description}}. Genius. While we're on the subject, though, it might be worth checking out _all_ of the fields the "accept" menu gives, and remove or re-target anything that isn't useful.

**Comment by primefac** [comment]
![image](https://user-images.githubusercontent.com/32815136/141327517-80d99c67-ad19-4ef7-a07f-238766a8154a.png)
 The above is for an accepted biography of a dead person. If "living" is chosen the death info doesn't show, and if the biography box isn't checked than none of the subsequent info shows.

**Comment by siddharthvp** [comment]
Looking at the source code, the script doesn't seem to use the values entered in "Description of the subject", "Month and day of birth", "Place of birth", "Month and day of death", "Place of death" anywhere at all – they're simply discarded!

**Comment by siddharthvp** [comment]
Opened #191 to remove those.

**Comment by enterprisey** [comment]
Indeed, the values don't seem to be used. That's remarkable.

For posterity, they used to be used for Persondata, but I removed that use in 9632e4fdd701178968867e9936e1d7eda77b1d8a and didn't think to remove them from the UI. That's a lot of wasted time spent filling those out... ah, better late than never.
