### ISSUE TITLE
Decline and reject messages sometimes sent to [[User talk:Null]]

### ISSUE THREAD

**Issue by NovemLinguae** [WPAFC/afch-rewrite#195]
Appears to have started on November 11, 2021, so likely related to a recent code change.

https://en.wikipedia.org/wiki/User_talk:Null

Discussion at: https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Script_misbehaving

**Comment by enterprisey** [comment]
should be alright; I've made a silly little patch to the onwiki version (https://en.wikipedia.org/w/index.php?diff=1054825110) that should probably not go into the official version. issue with wizard resolved, see discussion
