### ISSUE TITLE
Issue "generating-certificates"

### ISSUE THREAD

**Issue by PriyanshSarvehi** [WPAFC/afch-rewrite#201]
As according to the readme file I initiated npm start and it threw me this error:
![Screenshot 2021-11-23 041135](https://user-images.githubusercontent.com/92828382/142945953-289fadce-5c68-48d2-8d0f-09901b464044.png)
After running npm run generate-certificates it gave me this error:
![Screenshot 2021-11-23 041031](https://user-images.githubusercontent.com/92828382/142946048-3c1976f7-4f89-4fcf-b5c8-1850cbac2e12.png)
Can anyone help me resolving this issue? it would be of great help!

**Comment by dikshatakyar** [comment]
@PriyanshSarvehi try running the setup instructions on Git rather than windows cmd. I was facing the same error and it worked for me. :)

**Comment by PriyanshSarvehi** [comment]
@dikshatakyar yea i tried that too ......
I was encountering two issues:
1. I'm constantly facing one vulnerability issue which isnt being patched with npm audit fix command
2. after running npm run generate-certificates:
$ npm run generate-certificates

> afch-rewrite@0.9.1 generate-certificates A:\Coding\OpenSource\afch-rewrite
> node scripts/generate-certificates.js

You will be asked for a passphrase. You will not have to use it after this script is done. It must be 4 or more characters long. You will have to enter it four times in total.
Generating RSA private key, 2048 bit long modulus (2 primes)
............................+++++
.+++++
e is 65537 (0x010001)
Enter pass phrase for certificates\myCA.key:
and i cant enter anything at all


please help

**Comment by dikshatakyar** [comment]
@PriyanshSarvehi I guess when this paraphrase instruction ends,we have to enter any keyword which is >4 characters and it will be asked four times in the setup. when the instruction says `Enter pass phrase for certificates\myCA.key:` you have to write any keyword, as far as I remember it won't be visible on the cmd. So if you are thinking that you are typing something and it's not visible on the cmd it's fine just enter it whenever asked.
Hope this works.

**Comment by PriyanshSarvehi** [comment]
@dikshatakyar well it did 😅

**Comment by dikshatakyar** [comment]
@PriyanshSarvehi great,you're done with the setup?

**Comment by PriyanshSarvehi** [comment]
@dikshatakyar actually no 
Stuck again

**Comment by PriyanshSarvehi** [comment]
> @dikshatakyar yea i tried that too ...... I was encountering two issues:
> 
> 1. I'm constantly facing one vulnerability issue which isnt being patched with npm audit fix command
> 2. after running npm run generate-certificates:
>    $ npm run generate-certificates
> 
> > afch-rewrite@0.9.1 generate-certificates A:\Coding\OpenSource\afch-rewrite
> > node scripts/generate-certificates.js
> 
> You will be asked for a passphrase. You will not have to use it after this script is done. It must be 4 or more characters long. You will have to enter it four times in total. Generating RSA private key, 2048 bit long modulus (2 primes) ............................+++++ .+++++ e is 65537 (0x010001) Enter pass phrase for certificates\myCA.key: and i cant enter anything at all
> 
> please help

my problem #1 still persists

**Comment by PriyanshSarvehi** [comment]
also after npm start cmd just pops up 
what to do of it?

**Comment by dikshatakyar** [comment]
@PriyanshSarvehi , do you have grunt installed on your local machine ?

**Comment by PriyanshSarvehi** [comment]
Yes I have it installed @dikshatakyar

**Comment by enterprisey** [comment]
As of 739b17d36e542117f260c13e98c3cbc331b3fcf5, we don't use HTTPS any more, so enjoy the better dev experience :)
