### ISSUE TITLE
Unable to load Certificate in the browser

### ISSUE THREAD

**Issue by dikshatakyar** [WPAFC/afch-rewrite#203]
While loading the certificates in my browser, I can't see the file which we have to upload, which is myCA.pem . All it shows is a localhost file certificate when I select the certificates folder for uploading. 

![image](https://user-images.githubusercontent.com/75247382/143778344-03d62321-075e-44df-94a8-12ca5fe7cd1a.png)

I have asked doubts in Zulip as well (in enwiki-afch stream) but didn't get any response. I would be extremely grateful if anyone can help me resolve this issue. Thanks.

**Comment by cryptic-pr03** [comment]
can you verify whether myCA.pem is present in the directory or not.

**Comment by cryptic-pr03** [comment]
@dikshatakyar can you please verify whether myCA.pem is present in the directory or not.. 
If yes, then there are _4 tabs_ while loading certificate in Chrome "ubuntu". select the **Authority tab** and then import **myCA.pem**. 

![image](https://user-images.githubusercontent.com/92126782/145180861-7104644a-5c16-4e68-b540-7d1da22b56df.png)

Hope it helps :)

**Comment by dikshatakyar** [comment]
@cryptic-pr03 thanks for the help !

**Comment by enterprisey** [comment]
yeah sorry about all the bother... I'm thinking of getting rid of all of this nonsense with certificates soon, if I can be convinced that it's not a security issue
