### ISSUE TITLE
Userspace log

### ISSUE THREAD

**Issue by kzhovn** [WPAFC/afch-rewrite#227]
Allow the user to set a preference to create a userspace log, like Twinkle's CSD or PROD log, for accept/decline/rejects.

A minimal version might look something like

`# [[Draft title]] by [[User:DraftSubmiter]] {accept/decline/rejected} on {{subst:TIMESTAMP}}\n`

**Comment by NovemLinguae** [comment]
Related #134

**Comment by kzhovn** [comment]
One way to deal with volume might be to have an option to create monthly log pages instead of one large one.
