### ISSUE TITLE
Add "frequently used snippets" next to the decline reason box

### ISSUE THREAD

**Issue by APerson241** [WPAFC/afch-rewrite#31]
There's a lot of room next to the box for entering a comment while declining a submission:

![afch-request-frequently-used-snippets](https://cloud.githubusercontent.com/assets/1981364/5235672/d433d724-77da-11e4-9f9b-fd800c218592.PNG)

Why don't we use this for something like a list of frequently used snippets? The actions available for snippets would be adding, removing, and rearranging them. Snippets would be wikitext. If we're feeling adventurous, we could render the snippets on hover or something.

**Comment by APerson241** [comment]
Realized that this isn't necessarily a good thing; people have userspace pastebins for that.

**Comment by josve05a** [comment]
Sometimes I decline a few drafts that are "similar". Howabout having a last comments, or a way for the script to remember my last 1-3 custom rationale? Instead of having my copy-paste them?
