### ISSUE TITLE
Better preloading for duplicate declines

### ISSUE THREAD

**Issue by APerson241** [WPAFC/afch-rewrite#43]
Whenever a decline reason involving duplicates is selected, the script should preload the form more efficiently. Specifically:

 - When the "duplicate of a mainspace article" reason is selected, the script should preload the form with the name of the article.
 - When the "duplicate of a submission" reason is selected, the script should search across both the Draft namespace and the WT:AFC space for duplicates and then preload one.

**Comment by Lorwp** [comment]
Seems good, but the problem i see here is that how it’s going to work out if there’s a duplicate. The titles would not necessarily be the same unless there was one with the same name on both Namespaces.

**Comment by APerson241** [comment]
That's how I generally encounter duplicates. Either way, it's better to start with something in that field than with nothing.
