### ISSUE TITLE
Does not add AfC banner to other NS other that 0

### ISSUE THREAD

**Issue by josve05a** [WPAFC/afch-rewrite#50]
When accepting a Template through AfC, and add WikiProjects, it doesn't create a talk page. Also see this screenshot. No indication it even tried, but it did try to edit the Template twice, once with an editconflict (same thing happened on another Template-AfC just minutes before, so I see a pantern.)

![Screenshot]
(http://i.snag.gy/CR5iM.jpg)

**Comment by theopolisme** [comment]
Will be live shortly, cheers
