### ISSUE TITLE
Odd error.

### ISSUE THREAD

**Issue by josve05a** [WPAFC/afch-rewrite#58]
![screenshot 2015-04-27 at 15 31 54](https://cloud.githubusercontent.com/assets/7117013/7348533/aabaca14-ecf2-11e4-9686-518533675c91.png)
![screenshot 2015-04-27 at 11 49 24](https://cloud.githubusercontent.com/assets/7117013/7348532/aa9cd72a-ecf2-11e4-81c2-e0953e025513.png)

**Comment by APerson241** [comment]
Looks like the bot ran into a captcha. Maybe it hit some rate limits?

If this showed up during "slow" reviewing rates (maybe 1 every two minutes), then there would definitely be a problem here.

Marking as a bug anyway, as this error should be passed on in a more user-friendly way.

**Comment by theopolisme** [comment]
> Looks like the bot ran into a captcha.

What "bot"? The script isn't a bot, it's editing as the user... @josve05a, you might have triggered some sort of blacklist? Did the page have some questionable content?

**Comment by APerson241** [comment]
(Yeah, I meant script.)

**Comment by josve05a** [comment]
I think I know what happened. I got logged out (in another window/computer) which caused my to be not logged in while I edited (looks logged in since I entered the page before)...soemthing like that?

**Comment by theopolisme** [comment]
That makes a lot of sense! I'll count that as issue resolved :)
