### ISSUE TITLE
Deletion tags should block reviewing

### ISSUE THREAD

**Issue by APerson241** [WPAFC/afch-rewrite#61]
When the script sees `{{mfd}}` or another deletion tag (e.g. a CSD or PROD), it shouldn't allow the draft to be accepted or declined pending the resolution of the deletion discussion.

**Comment by Technical-13** [comment]
I disagree that "oh, there is a deletion tag on this page so it's going to be deleted anyways so it can't be improved and approved while the deletion discussion is open" is the path to take here. I think that if a reviewer comes along and finds that the draft is approvable, then the script should carry out the approval as is appropriate and remove any CSD or PROD tags. Obviously, it can't remove the tag for an unclosed MfD discussion, but it can still approve the request and I do agree that it should have an end result of the {{Mfd}} on the top of the resulting article. It should also post a procedural note on the MfD that a reviewer reviewer the draft and accepted it as a new article (which in of itself says the reviewer thinks the draft has at least a 50-80% chance of AfD survival, per the reviewing instructions).

**Comment by APerson241** [comment]
Per Technical-13.

Also, nobody would ever do this.
