### ISSUE TITLE
Review logs

### ISSUE THREAD

**Issue by josve05a** [WPAFC/afch-rewrite#62]
We already have CSD logs for copyvios etc. Why not implement 'review log'?Easier to clean up a bad reviewer's reviews and makes it a bit competative at the same time (and I love stats!)

**Comment by theopolisme** [comment]
Yup, I know this was on the roadmap at some point. I haven't touched the code in a while but it might be an interesting feature for someone to add. Technically it's quite simple.

**Comment by APerson241** [comment]
I currently have a web tool to get a list of a user's AfC reviews (much like the AfD stats tool) on the back burner, but it should be ready pretty soon.

In my opinion, these review logs would get pretty big pretty fast, especially with some of the more active reviewers; we might be better off with such a tool.

**Comment by theopolisme** [comment]
Link to APerson's project: https://github.com/APerson241/afchistory

**Comment by APerson241** [comment]
Resolved with the addition of that tool.
