### ISSUE TITLE
Categories get cut off

### ISSUE THREAD

**Issue by APerson241** [WPAFC/afch-rewrite#64]
While accepting, there seems to be a maximum length for categories. This is a big problem, as there are numerous categories that have very long names.

**Comment by theopolisme** [comment]
Example? The only operation we perform on the category names is a trim to remove whitespace... Maybe the API is returning truncated names? I wonder if there is an alternative mechanism by which to refer to categories (e.g. page identifiers) if this is truly an issue...

Relevant fn: https://github.com/WPAFC/afch-rewrite/blob/9632e4fdd701178968867e9936e1d7eda77b1d8a/src/modules/submissions.js#L624-L658

**Comment by APerson241** [comment]
Steps I followed to reproduce:

1. Visit a draft with the latest version of AFCH
2. Open AFCH
3. Hit "Accept"
4. Enter the "Add categories" field by clicking at the end
5. Hold down a key, or something

After a bit, the text string stops getting longer, when there should be no limit.

**Comment by theopolisme** [comment]
Oh, I think the problem you're encountering is that the category `<input>` element is actually being cut off in the display itself (I experienced this when following your steps to repro). This is probably due to a hacky tweak in which its width was set to `110%`:

> 		/*
>			Since we're hacking this dynamic suggestion feature into
>			jquery.chosen, we have to manually set the width of the input.
>			(see "Offer dynamic category suggestions" in submissions.js)
>		*/
>

I'll try a slightly less hacky fix shortly.

**Comment by theopolisme** [comment]
@APerson241 ^ fixed the issue for me, please test and close if it appears resolved for you as well.

**Comment by APerson241** [comment]
Fixed!
