### ISSUE TITLE
Warn if the draft page has a talk page

### ISSUE THREAD

**Issue by josve05a** [WPAFC/afch-rewrite#66]
https://en.wikipedia.org/wiki/Draft:Restaurant_%26_Bar_Design_Awards has a draft page saying it has an OTRS-tcket. Normally reviewers wouldn't notice this and mark it for deletetion anyways. The tool needs to warn that there is a talk page and/or an OTR-template on it.

**Comment by APerson241** [comment]
So, the way this'll work is if the copyright decline reason is selected and there's an OTRS template on the draft's talk page, a big (dismissable) notice pops up. Sounds good.

**Comment by APerson241** [comment]
Works on my box. Will test and merge later today.

**Comment by theopolisme** [comment]
Maybe the fact that there's an OTRS template on the talk page should be
surfaced to the reviewer prior to this point? I.e. as one of the
getSubmissionWarnings() shown in the orange box when AFCH is first loaded.
Its present placement works, but informing the reviewer of OTRS before they
start googling around to find a copyvio might be more efficient.

**Comment by APerson241** [comment]
I see where you're coming from. This would be another `checkXxx()` method nested in [`getSubmissionWarnings()`](https://github.com/WPAFC/afch-rewrite/blob/master/src/modules/submissions.js#L858), I guess.
