### ISSUE TITLE
Not starting or loading at all ("AFCH.Page is not a constructor" and "AFCH.load is not a function")

### ISSUE THREAD

**Issue by josve05a** [WPAFC/afch-rewrite#80]
`Uncaught TypeError: AFCH.Page is not a constructor https://en.wikipedia.org/w/index.php?action=raw&ctype=text/javascript&title=MediaWiki:Gadget-afchelper-beta.js/core.js:320`

`Uncaught TypeError: AFCH.load is not a function https://en.wikipedia.org/w/index.php?title=User:Enterprisey/afch-dev.js&action=raw&ctype=text/javascript:54`

On https://en.wikipedia.org/w/index.php?title=Draft:Program_Management_Professional&oldid=724401274

**Comment by josve05a** [comment]
It won't load or display as an opinion or tool in the "More" menu.

**Comment by APerson241** [comment]
Diagnosis was that josve05a was using the beta version of the script (i.e. pre-rewrite), and the fix was switching to the version I made in userspace by throwing together various parts of the beta scripts.

**Comment by enterprisey** [comment]
seems closed, I guess
