### ISSUE TITLE
Add option to put review comments on draft talk

### ISSUE THREAD

**Issue by Svetlana-T** [WPAFC/afch-rewrite#82]
The script needs to put draft reviewer comments on the draft talk page to make the draft easier to edit. This adds inconvenience to newcomers who don't even know that the talk page exists; measures against that are discussed on-wiki.

**Comment by enterprisey** [comment]
Moving the draft reviewer comments to the talk page on accept is #128; making the draft talk page the canonical location for comments needs a discussion on WT:WPAFC first.
