### ISSUE TITLE
Usernames that are part of a whitelisted username are erroneously whitelisted

### ISSUE THREAD

**Issue by MusikAnimal** [WPAFC/afch-rewrite#96]
I'm only guessing this based on https://github.com/WPAFC/afch-rewrite/blob/master/src/modules/core.js#L105

For example, User:Animal would be allowed to use the tool because User:MusikAnimal is on the whitelist.

Since this is an enwiki-only thing, I would suggest parsing out the usernames as they are entered now, so something like `(new RegExp('\|\s*' + user + '\s*}').test(text)`

**Comment by MusikAnimal** [comment]
Hey sorry, I think there is still a bug. The username interpolated into the regex could itself contain valid regex. For example, say the username is `Foo.bar`. With this, the username "Foo_bar" would get matched, because `.` means any character.

I think you need something more like this:
```javascript
// First get each row with usage of {{user2}}
var usernames = text.match(/{{\s*user2\s*\|.*?}}/g).map(function (row) {
  // Array.prototype.match with the g flag will return the full result,
  // not any groupings, so we need to again match to get the actual username.
  return row.match(/\|(.*?)}/)[1].trim();
});
// usernames is now an array of the actual usernames.
var userAllowed = usernames.indexOf(user) !== -1;
```

Yay parsing wikitext! =p

**Comment by enterprisey** [comment]
Thanks for noticing the bug! That's definitely one approach - I was thinking of just escaping the username so it's safe for a regex, too
