### ISSUE TITLE
Org admin

### ISSUE THREAD

**Issue by enterprisey** [WPAFC/afch-rewrite#97]
I was about to go into the settings and fix our CI settings, due to the upcoming deprecation of GitHub Services, but I found that I don't actually have owner access on this repo. Would it be possible for someone to grant that? Thanks!

cc @theopolisme @legoktm @Nathan2055

**Comment by legoktm** [comment]
Done. Please enable 2FA though!

**Comment by enterprisey** [comment]
I have enabled 2FA.
